name: Python Application

on:
  push:
    branches: [ main, feature/*, bugfix/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov flake8
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Check application structure
      run: |
        python -c "import os; print('Checking project structure:'); [print(f'- {d}') for d in os.listdir('.') if os.path.isdir(d) and not d.startswith('.')]"
        
    - name: Validate Streamlit app
      run: |
        if [ -f main.py ]; then
          python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
        fi 